// MEO.Synthesis — the marth's Enchanting Overhaul patcher as a Synthesis patch.
//
// Does what the standalone installer does, calling the SHARED Commands.* code
// (MEO.Installer/Commands.cs):
//   (a) rewrites the enchanting perk tree (AVEnchanting) to MEO's gem perks,
//       into Synthesis's own output mod, and
//   (b) derives + writes meo_calibration.json for this load order.

using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Synthesis.Settings;

return await SynthesisPipeline.Instance
    .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
    // Settings render in the Synthesis UI per-user; a missing file = defaults.
    .SetAutogeneratedSettings("Settings", "settings.json", out MEOSettingsHolder.Lazy)
    .SetTypicalOpen(GameRelease.SkyrimSE, "MEO - Patch.esp")
    .Run(args);

static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
{
    // Match the standalone installer's ESL flag: MEO - Patch.esp is a pure
    // override plugin, so it costs no load-order slot.
    state.PatchMod.IsSmallMaster = true;

    // Phase 3 auto-mint options (Synthesis settings UI; marth 2026-07-16
    // "as close to parity as possible" — multi-effect ON by default).
    Commands.MintMultiEffect = MEOSettingsHolder.Lazy.Value.MintMultiEffectRecipes;

    // (a) Perk-tree edit into Synthesis's output mod. Non-interactive KEEP-ALL —
    // Synthesis users curate foreign perks via their own load order. Uses
    // Synthesis's load order (Creation Club adds no enchanting perks).
    var rc = Commands.ApplyPatch(state.LoadOrder, state.LinkCache, state.PatchMod);
    if (rc != 0)
        throw new Exception($"MEO ApplyPatch failed (rc={rc}) — see log above");

    // (b) Calibration. Build the load order OURSELVES so it includes Creation
    // Club content (Skyrim.ccc). Synthesis's load order omits CC plugins that
    // aren't in plugins.txt — and on an Anniversary Edition install that is ALL
    // of them (CC loads via Skyrim.ccc, not plugins.txt). Relying on Synthesis's
    // load order dropped ~24% of conversions and an entire family (chaos) on a
    // real deck test. The standalone installer reads Skyrim.ccc for exactly this
    // reason; we mirror its ordering (base masters -> CC -> plugins) and resolve
    // every plugin from the data folder, so it matches for vanilla and MO2 alike.
    var catalogPath = Path.Combine(AppContext.BaseDirectory, "gem_catalog.json");
    var meoDir = Path.Combine(state.DataFolderPath, "SKSE", "Plugins", "MEO");
    Directory.CreateDirectory(meoDir);
    var calOutPath = Path.Combine(meoDir, "meo_calibration.json");

    var (calLo, calCache) = BuildCalibrationLoadOrder(state);
    var crc = Commands.WriteCalibration(calLo, calCache, catalogPath, calOutPath);
    if (crc != 0)
        throw new Exception($"MEO WriteCalibration failed (rc={crc}) — see log above");
}

// A load order that includes Creation Club (Skyrim.ccc), mirroring the standalone
// installer's ResolveGame ordering, so calibration coverage matches it.
static (LoadOrder<IModListingGetter<ISkyrimModGetter>>, ILinkCache) BuildCalibrationLoadOrder(
    IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
{
    string dataDir = state.DataFolderPath;
    string gameRoot = Directory.GetParent(dataDir)?.FullName ?? dataDir;
    string[] baseMasters = { "Skyrim.esm", "Update.esm", "Dawnguard.esm", "HearthFires.esm", "Dragonborn.esm" };

    var cccPath = Path.Combine(gameRoot, "Skyrim.ccc");
    var ccc = File.Exists(cccPath)
        ? File.ReadLines(cccPath).Select(l => l.Trim())
              .Where(l => l.Length > 0 && !l.StartsWith('#')).ToList()
        : new List<string>();

    var pluginsTxt = (string)state.LoadOrderFilePath;
    var active = File.Exists(pluginsTxt)
        ? File.ReadLines(pluginsTxt).Where(l => l.StartsWith('*'))
              .Select(l => l[1..].Trim()).ToList()
        : new List<string>();

    var files = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    foreach (var f in Directory.EnumerateFiles(dataDir))
        files.TryAdd(Path.GetFileName(f), f);

    var listings = new List<IModListingGetter<ISkyrimModGetter>>();
    foreach (var name in baseMasters.Concat(ccc).Concat(active)
                 .Distinct(StringComparer.OrdinalIgnoreCase))
    {
        if (name.Equals("MEO - Patch.esp", StringComparison.OrdinalIgnoreCase) ||
            name.Equals("MEO - Strip.esp", StringComparison.OrdinalIgnoreCase))
            continue;  // never read our own output
        if (!files.TryGetValue(name, out var full)) continue;
        var mod = SkyrimMod.CreateFromBinaryOverlay(
            new ModPath(ModKey.FromNameAndExtension(name), full), SkyrimRelease.SkyrimSE);
        listings.Add(new ModListing<ISkyrimModGetter>(mod, enabled: true));
    }
    var lo = new LoadOrder<IModListingGetter<ISkyrimModGetter>>(listings);
    return (lo, lo.ToImmutableLinkCache());
}

// Synthesis-rendered patcher settings (SetAutogeneratedSettings). The holder is
// a static home for the lazy because top-level locals can't be captured by the
// static RunPatch local function.
public class MEOSettings
{
    [SynthesisSettingName("Mint multi-effect recipes (BETA)")]
    [SynthesisTooltip("BETA. When a detected enchantment is one conceptual effect built from " +
        "several magic effects (a primary plus real sub-effects), carry the sub-effects on the " +
        "minted gem as riders — closest to parity with the original item. OFF mints " +
        "single-effect gems only; items whose extra effects can't be expressed keep their " +
        "original enchant.")]
    public bool MintMultiEffectRecipes = true;
}

static class MEOSettingsHolder
{
    public static Lazy<MEOSettings> Lazy = null!;
}
