// GENERATED by tools/gen_catalog_header.py — DO NOT EDIT.
// Source of truth: data/gem_catalog.json + out/.../meo_runtime.json (ESP forms).
#pragma once

#include <array>
#include <cstdint>

namespace meo {

// Thematic bucket for NPC/vendor spawn pools (m19). Order is frozen —
// generator THEMES list and plugin.cpp weight tables index by it.
enum class Theme : std::uint8_t {
    kFire, kFrost, kShock, kArcane, kDrain, kMartial, kRoguish, kHoly,
    kUtility, kCount
};

// Catalog class (m34): mechanical family. Facet Insight boosts skill (SKILL)
// and attribute (LINEAR) armor gems; the rest are elemental/utility/control.
enum class GemClass : std::uint8_t {
    kSkill, kLinear, kResist, kBinary, kAbsorb, kControl, kStagger, kSoulTrap, kOther
};

// Secondary effect riding on the gem's primary (m21, Marth: gems follow the
// load order's elemental recipe — frost carries slow, shock carries magicka
// bite, chaos carries all three elements). magnitude = primary × ratio.
struct GemRider {
    const char*   plugin;
    std::uint32_t mgefID;
    float         ratio;     // rider magnitude / primary magnitude
    float         duration;  // seconds (0 = instant)
};

struct GemDef {
    const char*          gid;        // stable identity, stored in the co-save
    const char*          name;       // display word: "<name> <I..V> <base item>"
    const char*          plugin;     // master file owning the effect MGEF
    std::uint32_t        mgefID;     // MGEF FormID local to that master
    std::array<float, 5> magnitude;  // per level I..V
    float                duration;   // effect duration (0 = on-contact instant)
    float                xpMult;     // level-threshold multiplier (0 = never levels)
    bool                 singleLevel;
    std::array<std::uint32_t, 5> gemItem;  // MEO.esp-local MISC FormID per level
    std::uint8_t         spawnWeight;  // copies in the loot pool (rarer = stronger)
    bool                 isArmor;      // true = constant self effect on worn armor
    Theme                theme;        // thematic bucket for NPC/vendor pools (m19)
    GemClass             gclass;       // catalog class — Facet Insight targets skill/attribute (m34)
    std::uint8_t         nRiders;      // 0..2 secondary effects
    std::array<GemRider, 2> riders;
};

inline constexpr GemDef kGems[] = {
    { "absorbhealth", "Absorb Health", "Skyrim.esm", 0x0AA155, { 6.8f, 11.0f, 15.3f, 19.6f, 23.8f }, 0.0f, 1.5f, false, { 0x000900, 0x000901, 0x000902, 0x000903, 0x000904 }, 1, false, Theme::kDrain, GemClass::kAbsorb, 0, {{ {} }} },
    { "absorbmagicka", "Absorb Magicka", "Skyrim.esm", 0x0AA156, { 12.8f, 20.4f, 28.9f, 36.5f, 44.2f }, 0.0f, 1.0f, false, { 0x000905, 0x000906, 0x000907, 0x000908, 0x000909 }, 3, false, Theme::kDrain, GemClass::kAbsorb, 0, {{ {} }} },
    { "absorbstamina", "Absorb Stamina", "Skyrim.esm", 0x0AA157, { 12.8f, 20.4f, 28.9f, 36.5f, 44.2f }, 0.0f, 1.0f, false, { 0x00090A, 0x00090B, 0x00090C, 0x00090D, 0x00090E }, 3, false, Theme::kDrain, GemClass::kAbsorb, 0, {{ {} }} },
    { "banish", "Banish", "Skyrim.esm", 0x0ACBB5, { 6.0f, 10.0f, 15.0f, 22.0f, 30.0f }, 30.0f, 0.6f, false, { 0x00090F, 0x000910, 0x000911, 0x000912, 0x000913 }, 5, false, Theme::kArcane, GemClass::kControl, 0, {{ {} }} },
    { "chaos", "Chaos", "Dragonborn.esm", 0x02C46B, { 5.1f, 8.5f, 11.9f, 14.4f, 17.8f }, 0.0f, 1.5f, false, { 0x000914, 0x000915, 0x000916, 0x000917, 0x000918 }, 1, false, Theme::kArcane, GemClass::kLinear, 2, {{ { "Dragonborn.esm", 0x02C46D, 1.0f, 0.0f }, { "Dragonborn.esm", 0x02C46C, 1.0f, 0.0f } }} },
    { "firedamage", "Fire", "Skyrim.esm", 0x04605A, { 8.5f, 13.6f, 18.7f, 24.6f, 29.8f }, 0.0f, 1.0f, false, { 0x000919, 0x00091A, 0x00091B, 0x00091C, 0x00091D }, 3, false, Theme::kFire, GemClass::kLinear, 0, {{ {} }} },
    { "fortifyalchemy", "Fortify Alchemy", "Skyrim.esm", 0x08B65C, { 12.0f, 17.0f, 22.0f, 27.0f, 32.0f }, 0.0f, 1.5f, false, { 0x00091E, 0x00091F, 0x000920, 0x000921, 0x000922 }, 1, true, Theme::kArcane, GemClass::kSkill, 0, {{ {} }} },
    { "fortifyalteration", "Fortify Alteration", "Skyrim.esm", 0x07A0F2, { 12.0f, 17.0f, 22.0f, 27.0f, 32.0f }, 0.0f, 1.0f, false, { 0x000923, 0x000924, 0x000925, 0x000926, 0x000927 }, 3, true, Theme::kArcane, GemClass::kSkill, 0, {{ {} }} },
    { "fortifyarchery", "Fortify Archery", "Skyrim.esm", 0x07A0FE, { 15.0f, 19.0f, 24.0f, 28.0f, 32.0f }, 0.0f, 1.0f, false, { 0x000928, 0x000929, 0x00092A, 0x00092B, 0x00092C }, 3, true, Theme::kMartial, GemClass::kSkill, 0, {{ {} }} },
    { "fortifyarticulation", "Fortify Articulation", "Skyrim.esm", 0x0F6906, { 10.0f, 16.0f, 21.0f, 26.0f, 32.0f }, 0.0f, 0.6f, false, { 0x00092D, 0x00092E, 0x00092F, 0x000930, 0x000931 }, 5, true, Theme::kRoguish, GemClass::kSkill, 0, {{ {} }} },
    { "fortifyblock", "Fortify Block", "Skyrim.esm", 0x07A0F3, { 13.0f, 18.0f, 22.0f, 27.0f, 32.0f }, 0.0f, 1.0f, false, { 0x000932, 0x000933, 0x000934, 0x000935, 0x000936 }, 3, true, Theme::kMartial, GemClass::kSkill, 0, {{ {} }} },
    { "fortifycarry", "Fortify Carry", "Skyrim.esm", 0x07A0F4, { 17.0f, 27.2f, 38.2f, 49.3f, 59.5f }, 0.0f, 1.0f, false, { 0x000937, 0x000938, 0x000939, 0x00093A, 0x00093B }, 3, true, Theme::kMartial, GemClass::kLinear, 0, {{ {} }} },
    { "fortifyconjuration", "Fortify Conjuration", "Skyrim.esm", 0x07A0F5, { 12.0f, 17.0f, 22.0f, 27.0f, 32.0f }, 0.0f, 1.0f, false, { 0x00093C, 0x00093D, 0x00093E, 0x00093F, 0x000940 }, 3, true, Theme::kArcane, GemClass::kSkill, 0, {{ {} }} },
    { "fortifydestruction", "Fortify Destruction", "Skyrim.esm", 0x07A0F6, { 12.0f, 17.0f, 22.0f, 27.0f, 32.0f }, 0.0f, 1.0f, false, { 0x000941, 0x000942, 0x000943, 0x000944, 0x000945 }, 3, true, Theme::kArcane, GemClass::kSkill, 0, {{ {} }} },
    { "fortifyhealrate", "Fortify Heal Rate", "Skyrim.esm", 0x07A0F8, { 17.0f, 27.2f, 38.2f, 49.3f, 59.5f }, 0.0f, 1.0f, false, { 0x000946, 0x000947, 0x000948, 0x000949, 0x00094A }, 3, true, Theme::kMartial, GemClass::kLinear, 0, {{ {} }} },
    { "fortifyhealth", "Fortify Health", "Skyrim.esm", 0x0493AA, { 17.0f, 27.2f, 38.2f, 49.3f, 59.5f }, 0.0f, 1.5f, false, { 0x00094B, 0x00094C, 0x00094D, 0x00094E, 0x00094F }, 1, true, Theme::kMartial, GemClass::kLinear, 0, {{ {} }} },
    { "fortifyheavyarmor", "Fortify Heavy Armor", "Skyrim.esm", 0x07A0F9, { 12.0f, 17.0f, 22.0f, 27.0f, 32.0f }, 0.0f, 1.0f, false, { 0x000950, 0x000951, 0x000952, 0x000953, 0x000954 }, 3, true, Theme::kMartial, GemClass::kSkill, 0, {{ {} }} },
    { "fortifyillusion", "Fortify Illusion", "Skyrim.esm", 0x07A0FA, { 12.0f, 17.0f, 22.0f, 27.0f, 32.0f }, 0.0f, 1.0f, false, { 0x000955, 0x000956, 0x000957, 0x000958, 0x000959 }, 3, true, Theme::kArcane, GemClass::kSkill, 0, {{ {} }} },
    { "fortifylightarmor", "Fortify Light Armor", "Skyrim.esm", 0x07A0FB, { 12.0f, 17.0f, 22.0f, 27.0f, 32.0f }, 0.0f, 1.0f, false, { 0x00095A, 0x00095B, 0x00095C, 0x00095D, 0x00095E }, 3, true, Theme::kRoguish, GemClass::kSkill, 0, {{ {} }} },
    { "fortifylockpicking", "Fortify Lockpicking", "Skyrim.esm", 0x07A0FC, { 15.0f, 19.0f, 24.0f, 28.0f, 32.0f }, 0.0f, 0.6f, false, { 0x00095F, 0x000960, 0x000961, 0x000962, 0x000963 }, 5, true, Theme::kRoguish, GemClass::kSkill, 0, {{ {} }} },
    { "fortifymagicka", "Fortify Magicka", "Skyrim.esm", 0x049504, { 17.0f, 27.2f, 38.2f, 49.3f, 59.5f }, 0.0f, 1.5f, false, { 0x000964, 0x000965, 0x000966, 0x000967, 0x000968 }, 1, true, Theme::kArcane, GemClass::kLinear, 0, {{ {} }} },
    { "fortifymagickarate", "Fortify Magicka Rate", "Skyrim.esm", 0x07A0FD, { 21.2f, 34.9f, 47.6f, 61.2f, 74.8f }, 0.0f, 1.5f, false, { 0x000969, 0x00096A, 0x00096B, 0x00096C, 0x00096D }, 1, true, Theme::kArcane, GemClass::kLinear, 0, {{ {} }} },
    { "fortifyonehanded", "Fortify One Handed", "Skyrim.esm", 0x07A0FF, { 15.0f, 19.0f, 24.0f, 28.0f, 32.0f }, 0.0f, 1.0f, false, { 0x00096E, 0x00096F, 0x000970, 0x000971, 0x000972 }, 3, true, Theme::kMartial, GemClass::kSkill, 0, {{ {} }} },
    { "fortifypersuasion", "Fortify Persuasion", "Skyrim.esm", 0x0D6933, { 15.0f, 19.0f, 24.0f, 28.0f, 32.0f }, 0.0f, 0.6f, false, { 0x000973, 0x000974, 0x000975, 0x000976, 0x000977 }, 5, true, Theme::kRoguish, GemClass::kSkill, 0, {{ {} }} },
    { "fortifypickpocket", "Fortify Pickpocket", "Skyrim.esm", 0x07A100, { 15.0f, 19.0f, 24.0f, 28.0f, 32.0f }, 0.0f, 0.6f, false, { 0x000978, 0x000979, 0x00097A, 0x00097B, 0x00097C }, 5, true, Theme::kRoguish, GemClass::kSkill, 0, {{ {} }} },
    { "fortifyrestoration", "Fortify Restoration", "Skyrim.esm", 0x07A101, { 10.0f, 16.0f, 21.0f, 26.0f, 32.0f }, 0.0f, 1.0f, false, { 0x00097D, 0x00097E, 0x00097F, 0x000980, 0x000981 }, 3, true, Theme::kArcane, GemClass::kSkill, 0, {{ {} }} },
    { "fortifyshouttimer", "Fortify Shout", "Skyrim.esm", 0x08850D, { 10.0f, 15.0f, 20.0f, 25.0f, 30.0f }, 0.0f, 1.0f, false, { 0x000982, 0x000983, 0x000984, 0x000985, 0x000986 }, 3, true, Theme::kMartial, GemClass::kSkill, 0, {{ {} }} },
    { "fortifysmithing", "Fortify Smithing", "Skyrim.esm", 0x07A102, { 12.0f, 17.0f, 22.0f, 27.0f, 32.0f }, 0.0f, 1.5f, false, { 0x000987, 0x000988, 0x000989, 0x00098A, 0x00098B }, 1, true, Theme::kMartial, GemClass::kSkill, 0, {{ {} }} },
    { "fortifysneak", "Fortify Sneak", "Skyrim.esm", 0x07A103, { 15.0f, 19.0f, 24.0f, 28.0f, 32.0f }, 0.0f, 1.0f, false, { 0x00098C, 0x00098D, 0x00098E, 0x00098F, 0x000990 }, 3, true, Theme::kRoguish, GemClass::kSkill, 0, {{ {} }} },
    { "fortifyspeechcraft", "Fortify Speechcraft", "Skyrim.esm", 0x07A104, { 10.0f, 16.0f, 21.0f, 26.0f, 32.0f }, 0.0f, 0.6f, false, { 0x000991, 0x000992, 0x000993, 0x000994, 0x000995 }, 5, true, Theme::kRoguish, GemClass::kSkill, 0, {{ {} }} },
    { "fortifystamina", "Fortify Stamina", "Skyrim.esm", 0x049507, { 12.8f, 20.4f, 28.9f, 36.5f, 44.2f }, 0.0f, 1.5f, false, { 0x000996, 0x000997, 0x000998, 0x000999, 0x00099A }, 1, true, Theme::kMartial, GemClass::kLinear, 0, {{ {} }} },
    { "fortifystaminarate", "Fortify Stamina Rate", "Skyrim.esm", 0x07A105, { 17.0f, 27.2f, 38.2f, 49.3f, 59.5f }, 0.0f, 1.0f, false, { 0x00099B, 0x00099C, 0x00099D, 0x00099E, 0x00099F }, 3, true, Theme::kMartial, GemClass::kLinear, 0, {{ {} }} },
    { "fortifytwohanded", "Fortify Two Handed", "Skyrim.esm", 0x07A106, { 15.0f, 19.0f, 24.0f, 28.0f, 32.0f }, 0.0f, 1.0f, false, { 0x0009A0, 0x0009A1, 0x0009A2, 0x0009A3, 0x0009A4 }, 3, true, Theme::kMartial, GemClass::kSkill, 0, {{ {} }} },
    { "frost", "Frost", "Skyrim.esm", 0x04605B, { 8.5f, 13.6f, 18.7f, 24.6f, 29.8f }, 0.0f, 1.0f, false, { 0x0009A5, 0x0009A6, 0x0009A7, 0x0009A8, 0x0009A9 }, 3, false, Theme::kFrost, GemClass::kLinear, 1, {{ { "Skyrim.esm", 0x0B72A0, 2.0f, 3.0f } }} },
    { "influenceconfdownlow", "Fear", "Skyrim.esm", 0x05B451, { 6.0f, 10.0f, 15.0f, 22.0f, 30.0f }, 30.0f, 0.6f, false, { 0x0009AA, 0x0009AB, 0x0009AC, 0x0009AD, 0x0009AE }, 5, false, Theme::kArcane, GemClass::kControl, 0, {{ {} }} },
    { "magickadamage", "Magicka", "Skyrim.esm", 0x05B44F, { 12.8f, 20.4f, 28.9f, 36.5f, 44.2f }, 0.0f, 1.0f, false, { 0x0009AF, 0x0009B0, 0x0009B1, 0x0009B2, 0x0009B3 }, 3, false, Theme::kDrain, GemClass::kLinear, 0, {{ {} }} },
    { "muffle", "Muffle", "Skyrim.esm", 0x092A57, { 0.5f, 1.0f, 1.0f, 1.0f, 1.0f }, 0.0f, 2.25f, false, { 0x0009B4, 0x0009B5, 0x0009B5, 0x0009B5, 0x0009B5 }, 3, true, Theme::kRoguish, GemClass::kBinary, 0, {{ {} }} },
    { "paralysis", "Stagger", "Skyrim.esm", 0x0ACBB6, { 0.3f, 0.4f, 0.5f, 0.6f, 0.75f }, 0.0f, 1.5f, false, { 0x0009B6, 0x0009B7, 0x0009B8, 0x0009B9, 0x0009BA }, 1, false, Theme::kRoguish, GemClass::kStagger, 0, {{ {} }} },
    { "resistdisease", "Resist Disease", "Skyrim.esm", 0x100E60, { 8.0f, 13.0f, 17.0f, 21.0f, 25.0f }, 0.0f, 1.0f, false, { 0x0009BB, 0x0009BC, 0x0009BD, 0x0009BE, 0x0009BF }, 3, true, Theme::kMartial, GemClass::kResist, 0, {{ {} }} },
    { "resistfire", "Resist Fire", "Skyrim.esm", 0x048C8B, { 8.0f, 13.0f, 17.0f, 21.0f, 25.0f }, 0.0f, 1.0f, false, { 0x0009C0, 0x0009C1, 0x0009C2, 0x0009C3, 0x0009C4 }, 3, true, Theme::kFire, GemClass::kResist, 0, {{ {} }} },
    { "resistfrost", "Resist Frost", "Skyrim.esm", 0x048F45, { 8.0f, 13.0f, 17.0f, 21.0f, 25.0f }, 0.0f, 1.0f, false, { 0x0009C5, 0x0009C6, 0x0009C7, 0x0009C8, 0x0009C9 }, 3, true, Theme::kFrost, GemClass::kResist, 0, {{ {} }} },
    { "resistmagic", "Resist Magic", "Skyrim.esm", 0x0B7A35, { 6.0f, 9.0f, 12.0f, 16.0f, 20.0f }, 0.0f, 1.0f, false, { 0x0009CA, 0x0009CB, 0x0009CC, 0x0009CD, 0x0009CE }, 3, true, Theme::kArcane, GemClass::kResist, 0, {{ {} }} },
    { "resistpoison", "Resist Poison", "Skyrim.esm", 0x0FF15E, { 8.0f, 13.0f, 17.0f, 21.0f, 25.0f }, 0.0f, 1.0f, false, { 0x0009CF, 0x0009D0, 0x0009D1, 0x0009D2, 0x0009D3 }, 3, true, Theme::kRoguish, GemClass::kResist, 0, {{ {} }} },
    { "resistshockt", "Resist Shock", "Skyrim.esm", 0x049295, { 8.0f, 13.0f, 17.0f, 21.0f, 25.0f }, 0.0f, 1.0f, false, { 0x0009D4, 0x0009D5, 0x0009D6, 0x0009D7, 0x0009D8 }, 3, true, Theme::kShock, GemClass::kResist, 0, {{ {} }} },
    { "shockdamage", "Shock", "Skyrim.esm", 0x04605C, { 8.5f, 13.6f, 18.7f, 24.6f, 29.8f }, 0.0f, 1.0f, false, { 0x0009D9, 0x0009DA, 0x0009DB, 0x0009DC, 0x0009DD }, 3, false, Theme::kShock, GemClass::kLinear, 1, {{ { "Skyrim.esm", 0x05B44F, 2.0f, 0.0f } }} },
    { "soultrap", "Soul Trap", "Skyrim.esm", 0x05B452, { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f }, 5.0f, 0.0f, true, { 0x0009DE, 0x0009DE, 0x0009DE, 0x0009DE, 0x0009DE }, 3, false, Theme::kArcane, GemClass::kSoulTrap, 0, {{ {} }} },
    { "staminadamage", "Stamina", "Skyrim.esm", 0x05B450, { 8.5f, 13.6f, 18.7f, 24.6f, 29.8f }, 0.0f, 1.0f, false, { 0x0009DF, 0x0009E0, 0x0009E1, 0x0009E2, 0x0009E3 }, 3, false, Theme::kDrain, GemClass::kLinear, 0, {{ {} }} },
    { "turnundead", "Turn Undead", "Skyrim.esm", 0x05B46B, { 6.0f, 10.0f, 15.0f, 22.0f, 30.0f }, 30.0f, 0.6f, false, { 0x0009E4, 0x0009E5, 0x0009E6, 0x0009E7, 0x0009E8 }, 5, false, Theme::kHoly, GemClass::kControl, 0, {{ {} }} },
    { "unarmeddamage", "Unarmed (Pugilist)", "Skyrim.esm", 0x0424E2, { 10.0f, 16.0f, 21.0f, 26.0f, 32.0f }, 0.0f, 1.0f, false, { 0x0009E9, 0x0009EA, 0x0009EB, 0x0009EC, 0x0009ED }, 3, true, Theme::kMartial, GemClass::kSkill, 0, {{ {} }} },
    { "waterbreathing", "Waterbreathing", "Skyrim.esm", 0x092A48, { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f }, 0.0f, 0.0f, true, { 0x0009EE, 0x0009EE, 0x0009EE, 0x0009EE, 0x0009EE }, 3, true, Theme::kUtility, GemClass::kBinary, 0, {{ {} }} },
    { "sundamage", "Sun", "Dawnguard.esm", 0x015719, { 8.5f, 13.6f, 18.7f, 24.6f, 29.8f }, 0.0f, 1.0f, false, { 0x0009EF, 0x0009F0, 0x0009F1, 0x0009F2, 0x0009F3 }, 3, false, Theme::kHoly, GemClass::kLinear, 0, {{ {} }} },
};

// Cumulative XP to reach level II..V, scaled per gem by xpMult (DESIGN §3).
inline constexpr std::array<float, 4> kXPThresholds = { 400.0f, 900.0f, 2800.0f, 7000.0f };

inline constexpr const char* kRoman[5] = { "I", "II", "III", "IV", "V" };

}  // namespace meo
