#!/usr/bin/env python3
"""Embed the weapon-gem catalog into the DLL as native/GemCatalog.h.

Reads data/gem_catalog.json (curves/tiers, canonical) and
out/SKSE/Plugins/MEO/meo_runtime.json (the generated ESP's MISC FormID for
each gem x level — authoritative, matches the shipped MEO.esp byte-for-byte).
No runtime JSON parsing in the DLL: no file paths to break, and the catalog
can never drift from the code that consumes it.

Weapon domain only (M3): armor gems are constant/self effects with their own
apply path, shipped in a later milestone. Run whenever gem_catalog.json or
the ESP changes: python3 tools/gen_catalog_header.py
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
catalog = json.load(open(os.path.join(ROOT, 'data/gem_catalog.json')))
runtime = json.load(open(os.path.join(ROOT, 'out/SKSE/Plugins/MEO/meo_runtime.json')))

# Effect-item duration by catalog class (magnitude carries the level curve).
DURATION = {'CONTROL': 30, 'SOULTRAP': 5}   # LINEAR/ABSORB/STAGGER = 0 (on-contact)

def display_name(name: str) -> str:
    """'Fire Damage' -> 'Fire' — the gem word that prefixes item names."""
    return name[:-7] if name.endswith(' Damage') else name

rows = []
for gid, d in sorted(catalog.items()):
    if d['domain'] != 'weapon':
        continue
    r = runtime[gid]
    ref = d['mgef_refs'][0]
    single = bool(d['single_level'])
    curve = [1.0] * 5 if single else [float(x) for x in d['curve']]
    # single-level gems only mint one MISC form; repeat it (levels II+ unused)
    forms = [int(r['forms'][str(lv if not single else 1)], 16) for lv in range(1, 6)]
    rows.append(
        '    {{ "{gid}", "{name}", "{plugin}", 0x{fid:06X}, '
        '{{ {curve} }}, {dur}.0f, {xp}f, {single}, {{ {forms} }} }},'.format(
            gid=gid, name=display_name(d['name']), plugin=ref['plugin'],
            fid=int(ref['fid'], 16),
            curve=', '.join(f'{v}f' for v in curve),
            dur=DURATION.get(d['class'], 0),
            xp=float(d['xp_mult']),
            single='true' if single else 'false',
            forms=', '.join(f'0x{f:06X}' for f in forms)))

header = f"""// GENERATED by tools/gen_catalog_header.py — DO NOT EDIT.
// Source of truth: data/gem_catalog.json + out/.../meo_runtime.json (ESP forms).
#pragma once

#include <array>
#include <cstdint>

namespace meo {{

struct GemDef {{
    const char*          gid;        // stable identity, stored in the co-save
    const char*          name;       // display word: "<name> <I..V> <base item>"
    const char*          plugin;     // master file owning the effect MGEF
    std::uint32_t        mgefID;     // MGEF FormID local to that master
    std::array<float, 5> magnitude;  // per level I..V
    float                duration;   // effect duration (0 = on-contact instant)
    float                xpMult;     // level-threshold multiplier (0 = never levels)
    bool                 singleLevel;
    std::array<std::uint32_t, 5> gemItem;  // MEO.esp-local MISC FormID per level
}};

inline constexpr GemDef kWeaponGems[] = {{
{chr(10).join(rows)}
}};

// Cumulative XP to reach level II..V, scaled per gem by xpMult (DESIGN §3).
inline constexpr std::array<float, 4> kXPThresholds = {{ 400.0f, 1200.0f, 3600.0f, 10000.0f }};

inline constexpr const char* kRoman[5] = {{ "I", "II", "III", "IV", "V" }};

}}  // namespace meo
"""
out = os.path.join(ROOT, 'native/GemCatalog.h')
open(out, 'w').write(header)
print(f'wrote {out}: {len(rows)} weapon gems')
